name: CI - Job Scraper Service

on:
  push:
    branches: ["main"]
    paths:
      - 'services/job-scraper/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'services/job-scraper/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/job-scraper
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: services/job-scraper/package-lock.json
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
